export const LEADERBOARD_ENTRIES = [
  { rank: 1, name: "Amara Okafor", score: 4820, accent: "text-amber-500" },
  { rank: 2, name: "David Adebayo", score: 4380, accent: "text-slate-500" },
  { rank: 3, name: "Maya Johnson", score: 4110, accent: "text-orange-500" },
  { rank: 4, name: "Solomon Udumizi", score: 3890, accent: "text-primary" },
  {
    rank: 5,
    name: "Zainab Bello",
    score: 3650,
    accent: "text-muted-foreground",
  },
  { rank: 6, name: "Chinedu Okoro", score: 3420, accent: "text-muted-foreground" },
  { rank: 7, name: "Aisha Ibrahim", score: 3280, accent: "text-muted-foreground" },
  { rank: 8, name: "Tunde Bakare", score: 3110, accent: "text-muted-foreground" },
  { rank: 9, name: "Grace Mensah", score: 2975, accent: "text-muted-foreground" },
  { rank: 10, name: "Daniel Kalu", score: 2840, accent: "text-muted-foreground" },
  { rank: 11, name: "Fatima Yusuf", score: 2710, accent: "text-muted-foreground" },
  { rank: 12, name: "Emeka Nwosu", score: 2585, accent: "text-muted-foreground" },
  { rank: 13, name: "Mariam Ali", score: 2460, accent: "text-muted-foreground" },
  { rank: 14, name: "Samuel Eze", score: 2330, accent: "text-muted-foreground" },
  { rank: 15, name: "Joy Osei", score: 2210, accent: "text-muted-foreground" },
  { rank: 16, name: "Ifeoma Obi", score: 2080, accent: "text-muted-foreground" },
  { rank: 17, name: "Kemi Adeyemi", score: 1965, accent: "text-muted-foreground" },
  { rank: 18, name: "Yusuf Bello", score: 1840, accent: "text-muted-foreground" },
] as const;
